import { Alert } from '@/types';
import { subDays } from 'date-fns';

export const mockAlerts: Alert[] = [
  // Referral waiting alerts
  {
    id: 'alert-001',
    type: 'referral_waiting',
    priority: 'medium',
    roleId: 'role-001',
    candidateId: 'cand-001',
    message: 'Alice Johnson has been waiting in review stage for 4 business days',
    createdDate: new Date(),
    dismissed: false,
    businessDaysWaiting: 4,
    escalated: false,
  },
  {
    id: 'alert-002',
    type: 'referral_waiting',
    priority: 'high',
    roleId: 'role-003',
    candidateId: 'cand-011',
    message: 'Kate Anderson has been waiting in review stage for 5 business days (ESCALATED)',
    createdDate: subDays(new Date(), 1),
    dismissed: false,
    businessDaysWaiting: 5,
    escalated: true,
  },
  {
    id: 'alert-003',
    type: 'referral_waiting',
    priority: 'medium',
    roleId: 'role-006',
    candidateId: 'cand-020',
    message: 'Tina Young has been waiting in review stage for 2 business days',
    createdDate: new Date(),
    dismissed: false,
    businessDaysWaiting: 2,
    escalated: false,
  },

  // Screening overdue alerts
  {
    id: 'alert-004',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-002',
    candidateId: 'cand-007',
    message: 'Grace Lee has been in screening stage for 7 business days (overdue)',
    createdDate: subDays(new Date(), 1),
    dismissed: false,
    businessDaysWaiting: 7,
  },
  {
    id: 'alert-005',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-004',
    candidateId: 'cand-014',
    message: 'Noah Harris has been in screening stage for 8 business days (overdue)',
    createdDate: subDays(new Date(), 2),
    dismissed: false,
    businessDaysWaiting: 8,
  },
  {
    id: 'alert-006',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-007',
    candidateId: 'cand-025',
    message: 'Yara Baker has been in screening stage for 6 business days (overdue)',
    createdDate: new Date(),
    dismissed: false,
    businessDaysWaiting: 6,
  },
  {
    id: 'alert-007',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-009',
    candidateId: 'cand-031',
    message: 'Ella Turner has been in screening stage for 7 business days (overdue)',
    createdDate: subDays(new Date(), 1),
    dismissed: false,
    businessDaysWaiting: 7,
  },
  {
    id: 'alert-008',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-011',
    candidateId: 'cand-038',
    message: 'Leo Stewart has been in screening stage for 8 business days (overdue)',
    createdDate: subDays(new Date(), 2),
    dismissed: false,
    businessDaysWaiting: 8,
  },
  {
    id: 'alert-009',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-014',
    candidateId: 'cand-046',
    message: 'Tara Murphy has been in screening stage for 9 business days (overdue)',
    createdDate: subDays(new Date(), 3),
    dismissed: false,
    businessDaysWaiting: 9,
  },
  {
    id: 'alert-010',
    type: 'screening_overdue',
    priority: 'high',
    roleId: 'role-005',
    candidateId: 'cand-018',
    message: 'Rachel Hall has been in screening stage for 15 business days (overdue)',
    createdDate: subDays(new Date(), 7),
    dismissed: false,
    businessDaysWaiting: 15,
  },

  // Low candidate count alerts
  {
    id: 'alert-011',
    type: 'low_candidate_count',
    priority: 'medium',
    roleId: 'role-005',
    message: 'UX Designer (Client: HealthTech Partners) has only 3 active candidates',
    createdDate: subDays(new Date(), 2),
    dismissed: false,
  },
  {
    id: 'alert-012',
    type: 'low_candidate_count',
    priority: 'medium',
    roleId: 'role-008',
    message: 'Engineering Manager (Client: TechCorp Inc.) has only 4 active candidates',
    createdDate: subDays(new Date(), 1),
    dismissed: false,
  },
  {
    id: 'alert-013',
    type: 'low_candidate_count',
    priority: 'medium',
    roleId: 'role-012',
    message: 'QA Engineer (Client: Enterprise Software Corp) has only 2 active candidates',
    createdDate: new Date(),
    dismissed: false,
  },

  // Hire notifications
  {
    id: 'alert-014',
    type: 'hire_notification',
    priority: 'low',
    roleId: 'role-002',
    candidateId: 'cand-010',
    message: 'Congratulations! Jack Taylor has been hired for Product Manager role',
    createdDate: subDays(new Date(), 1),
    dismissed: false,
  },

  // Weekly summaries
  {
    id: 'alert-015',
    type: 'weekly_screening_summary',
    priority: 'low',
    message: 'Weekly Screening Summary: 12 candidates in screening stage, average wait time 5.2 business days',
    createdDate: subDays(new Date(), 2),
    dismissed: false,
  },
  {
    id: 'alert-016',
    type: 'weekly_client_feedback_summary',
    priority: 'low',
    message: 'Weekly Client Feedback: 68% acceptance rate, 22% awaiting feedback, 10% rejected',
    createdDate: subDays(new Date(), 2),
    dismissed: false,
  },
];
