import { ChecklistItem } from '@/types';

export const mockChecklists: ChecklistItem[] = [
  // Client Onboarding
  {
    id: 'check-001',
    category: 'client_onboarding',
    description: 'Schedule and complete kick-off call with client',
    completed: true,
    completedDate: new Date('2025-12-01'),
    roleId: 'role-001',
    order: 1,
  },
  {
    id: 'check-002',
    category: 'client_onboarding',
    description: 'Schedule ongoing client syncs (done or n/a)',
    completed: true,
    completedDate: new Date('2025-12-01'),
    roleId: 'role-001',
    order: 2,
  },
  {
    id: 'check-003',
    category: 'client_onboarding',
    description: 'Add new client to platform',
    completed: true,
    completedDate: new Date('2025-12-02'),
    roleId: 'role-001',
    order: 3,
  },
  {
    id: 'check-004',
    category: 'client_onboarding',
    description: 'Create slack channel',
    completed: true,
    completedDate: new Date('2025-12-02'),
    roleId: 'role-001',
    order: 4,
  },
  {
    id: 'check-005',
    category: 'client_onboarding',
    description: 'Post role(s) onto Twill platform',
    completed: true,
    completedDate: new Date('2025-12-03'),
    roleId: 'role-001',
    order: 5,
  },
  {
    id: 'check-006',
    category: 'client_onboarding',
    description: 'Invite client to hiring portal',
    completed: true,
    completedDate: new Date('2025-12-03'),
    roleId: 'role-001',
    order: 6,
  },
  {
    id: 'check-007',
    category: 'client_onboarding',
    description: 'Initiate referral review and sourcing processes',
    completed: true,
    completedDate: new Date('2025-12-04'),
    roleId: 'role-001',
    order: 7,
  },

  // Candidate Review & Screening (1-3 Business Days)
  {
    id: 'check-008',
    category: 'candidate_review_screening',
    description: 'Review candidates submitted by member partners',
    completed: true,
    completedDate: new Date(),
    order: 1,
  },
  {
    id: 'check-009',
    category: 'candidate_review_screening',
    description: 'Review candidates submitted by members',
    completed: true,
    completedDate: new Date(),
    order: 2,
  },
  {
    id: 'check-010',
    category: 'candidate_review_screening',
    description: 'Review candidates submitted by TA sourcing',
    completed: false,
    order: 3,
  },
  {
    id: 'check-011',
    category: 'candidate_review_screening',
    description: 'Mark candidates as "qualified" or disqualified',
    completed: false,
    order: 4,
  },
  {
    id: 'check-012',
    category: 'candidate_review_screening',
    description: 'Conduct screening calls to vet qualified candidates',
    completed: false,
    order: 5,
  },
  {
    id: 'check-013',
    category: 'candidate_review_screening',
    description: 'Make submission decision (submit to client or pass)',
    completed: false,
    order: 6,
  },

  // Quality Control
  {
    id: 'check-014',
    category: 'quality_control',
    description: 'Monitor candidate pipeline daily to identify candidates falling through the cracks',
    completed: true,
    completedDate: new Date(),
    order: 1,
  },
  {
    id: 'check-015',
    category: 'quality_control',
    description: 'Ensure all submitted candidates are screened within 1-5 business day timeframe',
    completed: false,
    order: 2,
  },
  {
    id: 'check-016',
    category: 'quality_control',
    description: 'Follow up on any delayed or pending screens',
    completed: false,
    order: 3,
  },

  // Client Submission & Interview Tracking
  {
    id: 'check-017',
    category: 'client_submission_tracking',
    description: 'Submit vetted candidates to client',
    completed: true,
    completedDate: new Date(),
    order: 1,
  },
  {
    id: 'check-018',
    category: 'client_submission_tracking',
    description: 'Track candidate progress through each interview stage',
    completed: true,
    completedDate: new Date(),
    order: 2,
  },
  {
    id: 'check-019',
    category: 'client_submission_tracking',
    description: 'Update status in system as candidates move through the process',
    completed: false,
    order: 3,
  },
  {
    id: 'check-020',
    category: 'client_submission_tracking',
    description: 'Maintain communication with client on candidate status',
    completed: false,
    order: 4,
  },

  // Member Notifications
  {
    id: 'check-021',
    category: 'member_notifications',
    description: 'Notify members when referral is qualified and intro is needed',
    completed: true,
    completedDate: new Date(),
    order: 1,
  },
  {
    id: 'check-022',
    category: 'member_notifications',
    description: 'Notify members when disqualified by TA (with reason)',
    completed: false,
    order: 2,
  },
  {
    id: 'check-023',
    category: 'member_notifications',
    description: 'Notify members when candidate is moving into client process',
    completed: true,
    completedDate: new Date(),
    order: 3,
  },
  {
    id: 'check-024',
    category: 'member_notifications',
    description: 'Notify members when candidate is rejected during process',
    completed: false,
    order: 4,
  },
  {
    id: 'check-025',
    category: 'member_notifications',
    description: 'Notify members when candidate is placed',
    completed: false,
    order: 5,
  },
];
