import { Client } from '@/types';
import { subDays, subMonths } from 'date-fns';

export const mockClients: Client[] = [
  {
    id: 'client-001',
    name: 'TechCorp Inc.',
    company: 'TechCorp',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 3),
    lastContactDate: subDays(new Date(), 2),
    slackChannelId: 'tech-corp-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-002',
    name: 'DataFlow Systems',
    company: 'DataFlow',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 2),
    lastContactDate: subDays(new Date(), 1),
    slackChannelId: 'dataflow-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-003',
    name: 'CloudScale Solutions',
    company: 'CloudScale',
    status: 'not_responsive',
    onboardingDate: subMonths(new Date(), 4),
    lastContactDate: subDays(new Date(), 14),
    slackChannelId: 'cloudscale-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-004',
    name: 'FinTech Innovations',
    company: 'FinTech Innovations',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 1),
    lastContactDate: new Date(),
    slackChannelId: 'fintech-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-005',
    name: 'HealthTech Partners',
    company: 'HealthTech',
    status: 'deprioritized',
    onboardingDate: subMonths(new Date(), 5),
    lastContactDate: subDays(new Date(), 30),
    portalInviteSent: true,
  },
  {
    id: 'client-006',
    name: 'AI Dynamics',
    company: 'AI Dynamics',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 2),
    lastContactDate: subDays(new Date(), 3),
    slackChannelId: 'ai-dynamics-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-007',
    name: 'GreenEnergy Co',
    company: 'GreenEnergy',
    status: 'paused',
    onboardingDate: subMonths(new Date(), 6),
    lastContactDate: subDays(new Date(), 45),
    portalInviteSent: true,
  },
  {
    id: 'client-008',
    name: 'E-Commerce Plus',
    company: 'E-Commerce Plus',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 1),
    lastContactDate: subDays(new Date(), 1),
    slackChannelId: 'ecommerce-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-009',
    name: 'CyberSec Solutions',
    company: 'CyberSec',
    status: 'at_risk',
    onboardingDate: subMonths(new Date(), 3),
    lastContactDate: subDays(new Date(), 10),
    slackChannelId: 'cybersec-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-010',
    name: 'Mobile First Apps',
    company: 'Mobile First',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 2),
    lastContactDate: subDays(new Date(), 2),
    slackChannelId: 'mobile-first-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-011',
    name: 'Enterprise Software Corp',
    company: 'Enterprise Software',
    status: 'responding',
    onboardingDate: subMonths(new Date(), 4),
    lastContactDate: new Date(),
    slackChannelId: 'enterprise-hiring',
    portalInviteSent: true,
  },
  {
    id: 'client-012',
    name: 'Startup Accelerator',
    company: 'Startup Accelerator',
    status: 'churned',
    onboardingDate: subMonths(new Date(), 8),
    lastContactDate: subMonths(new Date(), 2),
    portalInviteSent: false,
  },
];
