import { Role } from '@/types';
import { subDays, subMonths } from 'date-fns';

export const mockRoles: Role[] = [
  // Sarah Johnson's roles (ta-001)
  {
    id: 'role-001',
    title: 'Senior Frontend Engineer',
    clientId: 'client-001',
    assignedTAId: 'ta-001',
    priority: 'high',
    createdDate: subMonths(new Date(), 2),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 8,
    timeToQualified: 5,
    estimatedRevenue: 45000,
    pipelineCounts: {
      submittedReferrals: 8,
      memberPartners: 3,
      members: 5,
      taSourcing: 2,
      validatedCandidates: 12,
      qualifiedAwaitingScreening: 4,
      qualifiedScreened: 8,
      disqualified: 15,
      submittedToClient: 6,
      awaitingClientFeedback: 2,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-002',
    title: 'Product Manager',
    clientId: 'client-002',
    assignedTAId: 'ta-001',
    priority: 'high',
    createdDate: subMonths(new Date(), 1),
    postedToPlatform: true,
    timeToFirstSubmission: 2,
    timeToInClientProcess: 7,
    timeToQualified: 4,
    estimatedRevenue: 55000,
    pipelineCounts: {
      submittedReferrals: 6,
      memberPartners: 2,
      members: 4,
      taSourcing: 1,
      validatedCandidates: 10,
      qualifiedAwaitingScreening: 3,
      qualifiedScreened: 7,
      disqualified: 8,
      submittedToClient: 5,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 1,
    },
  },
  {
    id: 'role-003',
    title: 'Backend Engineer',
    clientId: 'client-003',
    assignedTAId: 'ta-001',
    priority: 'low',
    createdDate: subMonths(new Date(), 3),
    postedToPlatform: true,
    timeToFirstSubmission: 5,
    timeToInClientProcess: 12,
    timeToQualified: 8,
    estimatedRevenue: 40000,
    pipelineCounts: {
      submittedReferrals: 4,
      memberPartners: 1,
      members: 3,
      taSourcing: 1,
      validatedCandidates: 6,
      qualifiedAwaitingScreening: 2,
      qualifiedScreened: 4,
      disqualified: 10,
      submittedToClient: 3,
      awaitingClientFeedback: 2,
      clientDisqualified: 0,
      clientApproved: 1,
      clientInterview1: 1,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-004',
    title: 'Data Scientist',
    clientId: 'client-004',
    assignedTAId: 'ta-001',
    priority: 'high',
    createdDate: subDays(new Date(), 20),
    postedToPlatform: true,
    timeToFirstSubmission: 4,
    timeToInClientProcess: 10,
    timeToQualified: 6,
    estimatedRevenue: 50000,
    pipelineCounts: {
      submittedReferrals: 10,
      memberPartners: 4,
      members: 6,
      taSourcing: 2,
      validatedCandidates: 14,
      qualifiedAwaitingScreening: 5,
      qualifiedScreened: 9,
      disqualified: 12,
      submittedToClient: 4,
      awaitingClientFeedback: 1,
      clientDisqualified: 0,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 1,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-005',
    title: 'UX Designer',
    clientId: 'client-005',
    assignedTAId: 'ta-001',
    priority: 'deprioritized',
    createdDate: subMonths(new Date(), 4),
    postedToPlatform: false,
    estimatedRevenue: 35000,
    pipelineCounts: {
      submittedReferrals: 2,
      memberPartners: 1,
      members: 1,
      taSourcing: 0,
      validatedCandidates: 3,
      qualifiedAwaitingScreening: 1,
      qualifiedScreened: 2,
      disqualified: 5,
      submittedToClient: 0,
      awaitingClientFeedback: 0,
      clientDisqualified: 0,
      clientApproved: 0,
      clientInterview1: 0,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },

  // Michael Chen's roles (ta-002)
  {
    id: 'role-006',
    title: 'DevOps Engineer',
    clientId: 'client-006',
    assignedTAId: 'ta-002',
    priority: 'high',
    createdDate: subMonths(new Date(), 1),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 9,
    timeToQualified: 5,
    estimatedRevenue: 48000,
    pipelineCounts: {
      submittedReferrals: 7,
      memberPartners: 3,
      members: 4,
      taSourcing: 2,
      validatedCandidates: 11,
      qualifiedAwaitingScreening: 4,
      qualifiedScreened: 7,
      disqualified: 13,
      submittedToClient: 5,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 1,
      hired: 0,
    },
  },
  {
    id: 'role-007',
    title: 'Mobile Developer (iOS)',
    clientId: 'client-010',
    assignedTAId: 'ta-002',
    priority: 'high',
    createdDate: subDays(new Date(), 30),
    postedToPlatform: true,
    timeToFirstSubmission: 2,
    timeToInClientProcess: 7,
    timeToQualified: 4,
    estimatedRevenue: 52000,
    pipelineCounts: {
      submittedReferrals: 9,
      memberPartners: 4,
      members: 5,
      taSourcing: 1,
      validatedCandidates: 13,
      qualifiedAwaitingScreening: 3,
      qualifiedScreened: 10,
      disqualified: 11,
      submittedToClient: 6,
      awaitingClientFeedback: 2,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 1,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-008',
    title: 'Engineering Manager',
    clientId: 'client-001',
    assignedTAId: 'ta-002',
    priority: 'low',
    createdDate: subMonths(new Date(), 2),
    postedToPlatform: true,
    timeToFirstSubmission: 6,
    timeToInClientProcess: 14,
    timeToQualified: 10,
    estimatedRevenue: 60000,
    pipelineCounts: {
      submittedReferrals: 3,
      memberPartners: 1,
      members: 2,
      taSourcing: 1,
      validatedCandidates: 5,
      qualifiedAwaitingScreening: 2,
      qualifiedScreened: 3,
      disqualified: 7,
      submittedToClient: 2,
      awaitingClientFeedback: 1,
      clientDisqualified: 0,
      clientApproved: 1,
      clientInterview1: 1,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-009',
    title: 'Machine Learning Engineer',
    clientId: 'client-006',
    assignedTAId: 'ta-002',
    priority: 'high',
    createdDate: subDays(new Date(), 25),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 10,
    timeToQualified: 5,
    estimatedRevenue: 58000,
    pipelineCounts: {
      submittedReferrals: 11,
      memberPartners: 5,
      members: 6,
      taSourcing: 3,
      validatedCandidates: 15,
      qualifiedAwaitingScreening: 6,
      qualifiedScreened: 9,
      disqualified: 14,
      submittedToClient: 5,
      awaitingClientFeedback: 2,
      clientDisqualified: 1,
      clientApproved: 2,
      clientInterview1: 1,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-010',
    title: 'Security Engineer',
    clientId: 'client-009',
    assignedTAId: 'ta-002',
    priority: 'high',
    createdDate: subDays(new Date(), 35),
    postedToPlatform: true,
    timeToFirstSubmission: 4,
    timeToInClientProcess: 11,
    timeToQualified: 7,
    estimatedRevenue: 47000,
    pipelineCounts: {
      submittedReferrals: 5,
      memberPartners: 2,
      members: 3,
      taSourcing: 1,
      validatedCandidates: 8,
      qualifiedAwaitingScreening: 3,
      qualifiedScreened: 5,
      disqualified: 9,
      submittedToClient: 3,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 1,
      clientInterview1: 1,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },

  // Emily Rodriguez's roles (ta-003)
  {
    id: 'role-011',
    title: 'Full Stack Engineer',
    clientId: 'client-008',
    assignedTAId: 'ta-003',
    priority: 'high',
    createdDate: subDays(new Date(), 28),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 9,
    timeToQualified: 5,
    estimatedRevenue: 46000,
    pipelineCounts: {
      submittedReferrals: 8,
      memberPartners: 3,
      members: 5,
      taSourcing: 2,
      validatedCandidates: 12,
      qualifiedAwaitingScreening: 4,
      qualifiedScreened: 8,
      disqualified: 12,
      submittedToClient: 5,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-012',
    title: 'QA Engineer',
    clientId: 'client-011',
    assignedTAId: 'ta-003',
    priority: 'low',
    createdDate: subMonths(new Date(), 2),
    postedToPlatform: true,
    timeToFirstSubmission: 5,
    timeToInClientProcess: 12,
    timeToQualified: 8,
    estimatedRevenue: 38000,
    pipelineCounts: {
      submittedReferrals: 4,
      memberPartners: 1,
      members: 3,
      taSourcing: 1,
      validatedCandidates: 6,
      qualifiedAwaitingScreening: 2,
      qualifiedScreened: 4,
      disqualified: 8,
      submittedToClient: 2,
      awaitingClientFeedback: 1,
      clientDisqualified: 0,
      clientApproved: 1,
      clientInterview1: 1,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-013',
    title: 'Technical Product Manager',
    clientId: 'client-004',
    assignedTAId: 'ta-003',
    priority: 'high',
    createdDate: subDays(new Date(), 22),
    postedToPlatform: true,
    timeToFirstSubmission: 2,
    timeToInClientProcess: 8,
    timeToQualified: 4,
    estimatedRevenue: 56000,
    pipelineCounts: {
      submittedReferrals: 7,
      memberPartners: 3,
      members: 4,
      taSourcing: 1,
      validatedCandidates: 11,
      qualifiedAwaitingScreening: 4,
      qualifiedScreened: 7,
      disqualified: 10,
      submittedToClient: 4,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 2,
      clientInterview1: 1,
      clientInterview2: 1,
      takeHomeExercise: 1,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-014',
    title: 'Site Reliability Engineer',
    clientId: 'client-002',
    assignedTAId: 'ta-003',
    priority: 'high',
    createdDate: subDays(new Date(), 32),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 10,
    timeToQualified: 6,
    estimatedRevenue: 49000,
    pipelineCounts: {
      submittedReferrals: 6,
      memberPartners: 2,
      members: 4,
      taSourcing: 2,
      validatedCandidates: 10,
      qualifiedAwaitingScreening: 3,
      qualifiedScreened: 7,
      disqualified: 11,
      submittedToClient: 4,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 2,
      clientInterview1: 1,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-015',
    title: 'Solutions Architect',
    clientId: 'client-011',
    assignedTAId: 'ta-003',
    priority: 'low',
    createdDate: subMonths(new Date(), 3),
    postedToPlatform: true,
    estimatedRevenue: 40000,
    pipelineCounts: {
      submittedReferrals: 3,
      memberPartners: 1,
      members: 2,
      taSourcing: 1,
      validatedCandidates: 5,
      qualifiedAwaitingScreening: 1,
      qualifiedScreened: 4,
      disqualified: 6,
      submittedToClient: 2,
      awaitingClientFeedback: 1,
      clientDisqualified: 0,
      clientApproved: 1,
      clientInterview1: 1,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },

  // David Park's roles (ta-004)
  {
    id: 'role-016',
    title: 'Frontend Developer (React)',
    clientId: 'client-008',
    assignedTAId: 'ta-004',
    priority: 'high',
    createdDate: subDays(new Date(), 18),
    postedToPlatform: true,
    timeToFirstSubmission: 2,
    timeToInClientProcess: 7,
    timeToQualified: 4,
    estimatedRevenue: 44000,
    pipelineCounts: {
      submittedReferrals: 9,
      memberPartners: 4,
      members: 5,
      taSourcing: 2,
      validatedCandidates: 14,
      qualifiedAwaitingScreening: 5,
      qualifiedScreened: 9,
      disqualified: 13,
      submittedToClient: 6,
      awaitingClientFeedback: 2,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 1,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-017',
    title: 'Data Engineer',
    clientId: 'client-002',
    assignedTAId: 'ta-004',
    priority: 'high',
    createdDate: subDays(new Date(), 26),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 9,
    timeToQualified: 5,
    estimatedRevenue: 47000,
    pipelineCounts: {
      submittedReferrals: 8,
      memberPartners: 3,
      members: 5,
      taSourcing: 2,
      validatedCandidates: 12,
      qualifiedAwaitingScreening: 4,
      qualifiedScreened: 8,
      disqualified: 14,
      submittedToClient: 5,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-018',
    title: 'Platform Engineer',
    clientId: 'client-006',
    assignedTAId: 'ta-004',
    priority: 'low',
    createdDate: subMonths(new Date(), 2),
    postedToPlatform: true,
    timeToFirstSubmission: 7,
    timeToInClientProcess: 15,
    timeToQualified: 11,
    estimatedRevenue: 42000,
    pipelineCounts: {
      submittedReferrals: 4,
      memberPartners: 1,
      members: 3,
      taSourcing: 1,
      validatedCandidates: 6,
      qualifiedAwaitingScreening: 2,
      qualifiedScreened: 4,
      disqualified: 9,
      submittedToClient: 2,
      awaitingClientFeedback: 1,
      clientDisqualified: 0,
      clientApproved: 1,
      clientInterview1: 1,
      clientInterview2: 0,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-019',
    title: 'Backend Engineer (Node.js)',
    clientId: 'client-010',
    assignedTAId: 'ta-004',
    priority: 'high',
    createdDate: subDays(new Date(), 24),
    postedToPlatform: true,
    timeToFirstSubmission: 3,
    timeToInClientProcess: 9,
    timeToQualified: 5,
    estimatedRevenue: 46000,
    pipelineCounts: {
      submittedReferrals: 7,
      memberPartners: 3,
      members: 4,
      taSourcing: 2,
      validatedCandidates: 11,
      qualifiedAwaitingScreening: 4,
      qualifiedScreened: 7,
      disqualified: 12,
      submittedToClient: 5,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 3,
      clientInterview1: 2,
      clientInterview2: 1,
      takeHomeExercise: 0,
      referenceChecks: 0,
      hired: 0,
    },
  },
  {
    id: 'role-020',
    title: 'Product Designer',
    clientId: 'client-004',
    assignedTAId: 'ta-004',
    priority: 'high',
    createdDate: subDays(new Date(), 21),
    postedToPlatform: true,
    timeToFirstSubmission: 2,
    timeToInClientProcess: 8,
    timeToQualified: 4,
    estimatedRevenue: 51000,
    pipelineCounts: {
      submittedReferrals: 6,
      memberPartners: 2,
      members: 4,
      taSourcing: 1,
      validatedCandidates: 10,
      qualifiedAwaitingScreening: 3,
      qualifiedScreened: 7,
      disqualified: 10,
      submittedToClient: 4,
      awaitingClientFeedback: 1,
      clientDisqualified: 1,
      clientApproved: 2,
      clientInterview1: 1,
      clientInterview2: 1,
      takeHomeExercise: 1,
      referenceChecks: 0,
      hired: 0,
    },
  },
];
